/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/network-test` | `/network-test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/assistants` | `/assistants`; params?: Router.UnknownInputParams; } | { pathname: `/assistants/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/network-test` | `/network-test`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/assistants` | `/assistants`; params?: Router.UnknownOutputParams; } | { pathname: `/assistants/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/network-test${`?${string}` | `#${string}` | ''}` | `/network-test${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/assistants${`?${string}` | `#${string}` | ''}` | `/assistants${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/network-test` | `/network-test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/assistants` | `/assistants`; params?: Router.UnknownInputParams; } | `/assistants/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/assistants/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
