/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-1` | `/budget/step-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-2` | `/budget/step-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-3` | `/budget/step-3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-4` | `/budget/step-4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-5` | `/budget/step-5`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-6` | `/budget/step-6`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-7` | `/budget/step-7`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-1` | `/budget/step-1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-2` | `/budget/step-2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-3` | `/budget/step-3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-4` | `/budget/step-4`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-5` | `/budget/step-5`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-6` | `/budget/step-6`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/budget/step-7` | `/budget/step-7`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-1${`?${string}` | `#${string}` | ''}` | `/budget/step-1${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-2${`?${string}` | `#${string}` | ''}` | `/budget/step-2${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-3${`?${string}` | `#${string}` | ''}` | `/budget/step-3${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-4${`?${string}` | `#${string}` | ''}` | `/budget/step-4${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-5${`?${string}` | `#${string}` | ''}` | `/budget/step-5${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-6${`?${string}` | `#${string}` | ''}` | `/budget/step-6${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/budget/step-7${`?${string}` | `#${string}` | ''}` | `/budget/step-7${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-1` | `/budget/step-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-2` | `/budget/step-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-3` | `/budget/step-3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-4` | `/budget/step-4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-5` | `/budget/step-5`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-6` | `/budget/step-6`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/budget/step-7` | `/budget/step-7`; params?: Router.UnknownInputParams; };
    }
  }
}
